# Generated by Django 3.2.13 on 2023-05-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.DateField()),
                ('n_musicas', models.CharField(max_length=50)),
                ('real', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.DateField()),
                ('downloads', models.CharField(max_length=50)),
                ('aplicativo', models.BooleanField()),
            ],
        ),
    ]
